### ISSUE TITLE
How did you open the game on a PC?

### ISSUE THREAD

**Issue by RP-developer-01** [phen0menon/blum-autoclicker#1]
How did you open the game on a PC? Blum took away the ability to open the game on a PC. did you use emulators?

**Comment by phen0menon** [comment]
What do you mean? I can still open it without any problem, I'm on Windows 11, Telegram official client.

**Comment by RP-developer-01** [comment]
I have windows 10 in the official telegram client does not open the game blum
![photo_2024-07-05_15-06-04](https://github.com/phen0menon/blum-autoclicker/assets/98476877/72d1ad98-b5b2-4b1a-a58a-8d190b2c76ab)

**Comment by phen0menon** [comment]
Scroll down a little bit, bro..
