### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by alirezahasheminezhad** [phen0menon/blum-autoclicker#10]
![photo_2024-08-02_18-01-41](https://github.com/user-attachments/assets/49aa6743-60fa-48fa-8ac5-ca9da1be275d)
  same issue like last issue
  python -V : 3.11.9
  i tried all pythone version that u suggested
  please help man
  thanks !

**Comment by JMarshallst** [comment]
I have same issue using latest python, but its like having trouble about this ultralytics

**Comment by phen0menon** [comment]
I've updated README, can you try again?
