### ISSUE TITLE
CODE IS RUNNING FINE BUT I'm having another issue.

### ISSUE THREAD

**Issue by legiondreamz21** [phen0menon/blum-autoclicker#13]
as I play blum and run the code, it can't click the BLUMS , maybe my video card can't detect it? I'm using GT730

But the auto replay works

ERROR:
Found GPU0 NVIDIA GeForce GT 730 which is of cuda capability 3.5.
    PyTorch no longer supports this GPU because it is too old.
    The minimum cuda capability supported by this library is 3.7.

**Comment by phen0menon** [comment]
Hey @legiondreamz21, I'm not sure I can help with that, since the bot uses modern versions of PyTorch. However, you can try fixing it by yourself: https://discuss.pytorch.org/t/solved-pytorch-no-longer-supports-this-gpu-because-it-is-too-old/15444/45?page=2

**Comment by legiondreamz21** [comment]
Okay thanksss
