### ISSUE TITLE
Could not find a version that satisfies the requirement pywin32

### ISSUE THREAD

**Issue by hungngo-dayone** [phen0menon/blum-autoclicker#15]
I've problem with Mac OS device

ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none)
ERROR: No matching distribution found for pywin32

<img width="732" alt="iShot_2024-09-08_10 09 50 PM" src="https://github.com/user-attachments/assets/ac0fb2c1-1ba8-4310-a5dc-b45361342357">

**Comment by phen0menon** [comment]
This package is only for Windows.
