### ISSUE TITLE
Something strange...

### ISSUE THREAD

**Issue by iKor1** [phen0menon/blum-autoclicker#3]
Друг, привет
![2024-07-06 19_38_09-TelegramDesktop](https://github.com/phen0menon/blum-autoclicker/assets/174889136/9bac1355-d416-4099-979e-c22650848e01)
что делать с этим? Подскажи, пожалуйста.

**Comment by iKor1** [comment]
переустанавливать уже пробовал

**Comment by phen0menon** [comment]
сначала это запусти чтобы удалить текущие пакеты пайторча:

```
pip uninstall torch torchvision torchaudio
```

потом это чтобы заново установить:

```
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
```

upd. ну а вообще скинь полный лог ошибки.

**Comment by iKor1** [comment]
> сначала это запусти чтобы удалить текущие пакеты пайторча:
> 
> ```
> pip uninstall torch torchvision torchaudio
> ```
> 
> потом это чтобы заново установить:
> 
> ```
> pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
> ```
> 
> upd. ну а вообще скинь полный лог ошибки.

Я уже пробовал сделать как ты сказал, не помогло(
Я скинул полный лог, эта штука еще дергается, еле еле смог заскринить.

**Comment by phen0menon** [comment]
Вот как можно скинуть полный лог:

1. Запускаешь программу
2. Как только первая ошибка появляется, жмешь букву l и потом Ctrl + C. Окно не закроется, а лог будет доступен полный. Вот его и надо будет СКОПИРОВАТЬ, а не заскриншотить.
