### ISSUE TITLE
Задержка

### ISSUE THREAD

**Issue by Bashiragaev** [phen0menon/blum-autoclicker#5]
Как решить?
![image](https://github.com/phen0menon/blum-autoclicker/assets/19514012/09dce492-53ab-487c-8b95-48239e287f50)

**Comment by phen0menon** [comment]
Какая система у вас (интересует проц + видеокарта)?

А вообще, откройте еще раз инструкцию и там есть пункт "проблемы".

**Comment by Bashiragaev** [comment]
> Какая система у вас (интересует проц + видеокарта)?
> 
> А вообще, откройте еще раз инструкцию и там есть пункт "проблемы".

У маня ryzen 7 5700x и rx 7800 xt и по инструкции я делал не помогло

**Comment by phen0menon** [comment]
Тут я, наверное, мало помочь смогу, потому что у тебя AMD видеокарта, у них нету CUDA ядер, на котором работает мой кликер (там нейросетка которая улавливает объекты на экране)

**Comment by Bashiragaev** [comment]
Бля и тут фанатики зеленых
