### ISSUE TITLE
Не срабатывает нажатие

### ISSUE THREAD

**Issue by BLACKBUSTER777** [phen0menon/blum-autoclicker#6]
Заметил частенько происходит так, что происходят то ли мисклики по объектам, то ли во время наведения на них не срабатывает нажатие. (часто происходит так, что курсор возвращается по несколько раз к одной и той же фигуре, но не прожимает её)

**Comment by BLACKBUSTER777** [comment]
может это я что-то не так настроил хз (время отклика примерно 40ms)

**Comment by phen0menon** [comment]
Это нормально - я это сделал, чтобы не было прокликов на кнопку "закрытия" или "назад", чтобы бот не кликал туда, куда не надо, когда только появляется объект сверху.

Убедись, что у тебя масштабирование внутри телеграмма 100%, а также на винде ровно 100%. Если масштабирование стоит - тогда миссклики будут работать не так, как я задумывал.

А вообще, рандомные клики я тоже сделал, чтобы (если вдруг оно есть) анти-бот система не спалила (было бы странно что у тебя 100 из 100 кликов идут ровно на объекты).

**Comment by phen0menon** [comment]
А какая у тебя видеокарта?

**Comment by NEO-STALKER** [comment]
Приветствую. У меня максимум 140 балов набирается (из за бомб иногда больше). Видеокарта 1060 на 6 Гб.

**Comment by phen0menon** [comment]
Уже не актуально думаю - они убрали последнее обновление. 

Подумаю над тем, как оптимизировать и выкачу свежую версию под зеленые цветочки.
