### ISSUE TITLE
clear instruction needed

### ISSUE THREAD

**Issue by Alchemist786** [phen0menon/blum-autoclicker#8]
give some clear installation guide man, hours wasted yet could not make it work

**Comment by Alchemist786** [comment]
i cant get any of the pip command to run,not trying to sound like an idiot but non coder here

**Comment by phen0menon** [comment]
Did you install Python? What's your OS?

**Comment by bluevos** [comment]
@phen0menon hello bro why it be like this when run python main.py

![image](https://github.com/user-attachments/assets/1132710a-d6e5-4dcf-918f-75d17c313724)

**Comment by phen0menon** [comment]
@bluevos Please run this command: `python -V` and send here your python version.

**Comment by bluevos** [comment]
@phen0menon Python 3.12.4 should be
![image](https://github.com/user-attachments/assets/7426d8fa-6c1d-46fa-9e7b-e2daced23559)

**Comment by phen0menon** [comment]
@bluevos Please try Python 3.11 or 3.9, if it helps, I will update documentation.

**Comment by bluevos** [comment]
@phen0menon how to uninstall the python?

**Comment by bluevos** [comment]
@phen0menon i use both 3.11 and 3.9 it has this issue

![image](https://github.com/user-attachments/assets/4be14e1b-bc93-4771-82a4-b9837596ce6b)

**Comment by phen0menon** [comment]
Please refer to instructions and reproduce all steps from it

**Comment by Alchemist786** [comment]
> Please refer to instructions and reproduce all steps from it

can you make an youtube video?

**Comment by Alchemist786** [comment]
![p](https://github.com/user-attachments/assets/88346bb7-2e77-475f-99b8-41e3cfb0c1f2)
this is what im getting

**Comment by Alchemist786** [comment]
> Please refer to instructions and reproduce all steps from it

when i run the main file after all steps, nothing happens

**Comment by Alchemist786** [comment]
tried everything guys, it doesnt work, dont waste your time.
